Change from assay_name to assay.type
alanocallaghan/scater pull request #194
Opened 2023-02-17 19:10 UTC by antagomir

This should fix #189 as discussed.

The chance concerns only the arguments containing `a``ssay_name`, changing these argument names from underscore type to dot type.

Changing all other argument names in this way, or reviewing other argument names where this would support interoperability with _scuttle_ would be a heavier undertaking, perhaps best dealt with if specific needs will arise. Otherwise that will be mainly a stylistic issue.

2023-02-18 06:24 UTC, antagomir commented
The latest commit adds the Deprecation messages.

Meanwhile I noticed that at least the following arguments are shared with or passed to _scuttle_, which has already moved to using dot names for arguments and deprecated these versions. I could add a similar change for these arguments in the same or another PR if you agree. It seems that the change should be done at the latest when _scuttle_ removes these arguments from deprecation stage

- `check_names` (perFeatureDF arguments; within the `ggfeatures` function I already updated to call check.names for the scuttle call)
- `use_altexps`
- `prefix_altexps`
- `use_dimred` -> this is dimred in _scater_ and  use.dimred in _scuttle_

2023-02-18 16:26 UTC, Alanocallaghan commented
Can you revert to [6c30bee](https://github.com/Alanocallaghan/scater/pull/194/commits/6c30beee89b1f23a2201a77d463eccd4722f77c3)? I don't want to add deprecation messages within this cycle.

2023-02-18 16:29 UTC, Alanocallaghan commented
Also if you were adding deprecation messages the message should only pop up when somebody actually uses the old argument name. As-is people would get a deprecation message even if they were using the new argument name or not using either.

Something like

```r
if (!missing(exprs_values)) {
  .Deprecated(msg="message")
}
```

2023-02-18 17:01 UTC, antagomir commented
Ah I got it wrong when you gave the small comment that that the exprs_values is not deprecated. I thought it meant that the deprecation messages should be added.

I have now reverted to where it was before that comment.

I agree about the check before deprecation message, should have noticed that.

The question about the other arguments remains. I have listed above other arguments that scuttle has already deprecated (with message), and which are called in scater with their old names. It is possible to add those in this PR, or another new PR.

Is there something that still specifically has to be changed for this PR?

2023-02-18 17:40 UTC, Alanocallaghan commented
I haven't checked over the scuttle stuff yet, I think this PR is fine - if I want to change the other args I can do that myself anyways

2023-02-18 18:40 UTC, antagomir commented
Ok great. Just let me know if anything still needs to be changed before merging. The checks seems to pass at least.

2023-03-07 23:06 UTC, antagomir commented
The PR is ready from my side at least.

2023-03-08 10:08 UTC, Alanocallaghan commented
Can you see my review comments this time?

2023-03-08 10:12 UTC, Alanocallaghan requested changes
Bump the date and version, and fix the recursive alias

2023-03-08 10:12 UTC, alanocallaghan commented on R/plotExpression.R
> +#' for use in point aesthetics - see the \code{assay.type} argument in \code{?\link{retrieveCellInfo}}. Also the alias \code{by.assay.type} is accepted.
`by.assay.type` can't be an alias for `by.assay.type`?

2023-03-08 10:12 UTC, alanocallaghan commented on R/plotExpression.R
> +#' @param assay.type A string or integer scalar specifying which assay in \code{assays(object)} to obtain expression values from. Also the alias \code{assay.type} is accepted.
`assay.type` isn't alias for itself

2023-03-09 19:29 UTC, antagomir commented on R/plotExpression.R
> +#' for use in point aesthetics - see the \code{assay.type} argument in \code{?\link{retrieveCellInfo}}. Also the alias \code{by.assay.type} is accepted.
Fixed now in the PR update (coming).

2023-03-09 19:30 UTC, antagomir commented on R/plotExpression.R
> +#' @param assay.type A string or integer scalar specifying which assay in \code{assays(object)} to obtain expression values from. Also the alias \code{assay.type} is accepted.
done

2023-03-09 21:17 UTC, Alanocallaghan approved these changes

2023-03-09 21:17 UTC, antagomir commented
I did not receive any notification on the review comments but now noticed them. I have added these in the latest push, hopefully all ok but if not then let's continue to finalize.

2023-03-09 21:18 UTC, Alanocallaghan commented
Thanks! Sorry for the delay in looking at it

2023-03-09 21:34 UTC, antagomir commented
I would be looking fwd to having updates pushed to Bioconductor, then we could adopt these in downstream packages and tutorials.

2023-03-10 09:51 UTC, merged

2023-03-10 09:52 UTC, Alanocallaghan commented
Devel branch is pushed to bioc

2023-03-10 10:41 UTC, antagomir commented
Awesome - thanks!